version: '2.1'
orbs:
  node: circleci/node@4.6.0
  coveralls: coveralls/coveralls@1.0.6
jobs:
  unit_tests_coverage:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command:
            yarn coverage
      - coveralls/upload:
          parallel: true

  integration_tests_coverage:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command:
            yarn coverage:integration
      - coveralls/upload:
          parallel: true

  unit_tests:
    executor:
      name: node/default
      tag: '15.11'
    resource_class: xlarge
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run unit tests"
          command: yarn test

  solhint:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run solhint and lint-check"
          command: |
            yarn solhint
            yarn lint-check

  coverage:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run coverage"
          command: yarn coverage
      - coveralls/upload
      - store_artifacts:
          path: coverage
          prefix: coverage

  integration_tests:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run integration tests"
          command: yarn test:integration

  save_and_upload_coverage_artifacts:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - coveralls/upload:
          parallel_finished: true
      - store_artifacts:
          path: coverage
          prefix: coverage

  localDeployment:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Deploy on local network"
          command: yarn deploy-ci

  localDeploymentForkMainnet:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Deploy on forked mainnet"
          command: yarn deploy-ci:fork:mainnet

  runMythX-Pool:
    docker:
      - image: tempusfinance/tempus-mythx:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run mythx"
          no_output_timeout: 30m
          command: yarn mythx-pool

  runMythX-AMM:
    docker:
      - image: tempusfinance/tempus-mythx:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run mythx"
          no_output_timeout: 30m
          command: yarn mythx-amm

  runMythX-Misc:
    docker:
      - image: tempusfinance/tempus-mythx:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run mythx"
          no_output_timeout: 30m
          command: yarn mythx-misc

  echidna-lido-pool:
    docker:
      - image: tempusfinance/tempus-echidna:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run Echidna lido pool"
          no_output_timeout: 30m
          command: |
            yarn echidna-test:pool:lido
  
  echidna-yearn-pool:
    docker:
      - image: tempusfinance/tempus-echidna:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run Echidna yearn pool"
          no_output_timeout: 30m
          command: |
            yarn echidna-test:pool:yearn

  echidna-assertion-lido-pool:
    docker:
      - image: tempusfinance/tempus-echidna:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run Echidna assertion lido pool"
          no_output_timeout: 30m
          command: |
            yarn echidna-test-assertion:pool:lido

  echidna-assertion-yearn-pool:
    docker:
      - image: tempusfinance/tempus-echidna:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run Echidna assertion yearn pool"
          no_output_timeout: 30m
          command: |
            yarn echidna-test-assertion:pool:yearn

workflows:
  code_coverage:
    jobs:
      - unit_tests_coverage:
          context: 
            - Coveralls
      - integration_tests_coverage:
          context: 
            - Coveralls
      - save_and_upload_coverage_artifacts:
          context: 
            - Coveralls
          requires:
              - unit_tests_coverage
              - integration_tests_coverage
  unit_tests:
    jobs:
      - unit_tests
  integration_tests:
    jobs:
      - integration_tests
  solhint:
    jobs:
      - solhint
  test_local_deployment:
    jobs:
      - localDeployment
  test_local_deployment_fork_mainnet:
    jobs:
      - localDeploymentForkMainnet
  mythx_pool:
    jobs:
      - runMythX-Pool
  mythx_amm:
    jobs:
      - runMythX-AMM
  mythx_misc:
    jobs:
      - runMythX-Misc
  echidna:
    jobs:
      - echidna-lido-pool
      - echidna-yearn-pool
      - echidna-assertion-lido-pool
      - echidna-assertion-yearn-pool

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}