version: '2.1'
orbs:
  node: circleci/node@4.3.0
jobs:
  solhint:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: |
            npm run solhint
            npm run lint-check
workflows:
  testsol_and_solhint:
    jobs:
      - node/test
      - solhint