version: '2.1'
orbs:
  node: circleci/node@4.6.0
  coveralls: coveralls/coveralls@1.0.4
jobs:
  unit_tests:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
  solhint:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: |
            yarn solhint
            yarn lint-check
  coverage:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command:
            yarn coverage
      - coveralls/upload
      - store_artifacts:
          path: coverage
          prefix: coverage
  localDeployment:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command:
            yarn deploy-ci

workflows:
  unit_tests:
    jobs:
      - unit_tests
  solhint:
    jobs:
      - solhint
  code_coverage:
    jobs:
      - coverage:
          context: 
            - Coveralls
  test_local_deployment:
    jobs:
      - localDeployment

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}
